-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "gross_amount" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "stripe_fee" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "net_amount" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "stripe_transaction_id" VARCHAR(255);
